---
title: "Medicaid Cuts Out X"
description: ""
author: "Michael Kuhn"
date: "3/1/2025"
draft: true
output: html_document
categories:
  - medicaid
  - budget
  - policy
editor_options: 
  chunk_output_type: console
---


```{r}
#| include: false

library(tidyverse)
library(tidycensus)
library(tigris)
library(dotenv)
load_dot_env(file = ".env")

census_api_key(Sys.getenv('CENSUS_KEY'))

options(tigris_use_cache = TRUE)

```

Medicaid is the health insurance program for people with limited resources.

It is X percent of the federal budget. 


Income from census

walk down enrollment state level

https://data.medicaid.gov/dataset/6165f45b-ca93-5bb5-9d06-db29c692a360#data-table


```{r}

poverty_cd_s1701 <- get_acs(geography = "congressional district", 
        table = 'S1701',
        year = 2023,
        geometry = TRUE,
        cache_table = TRUE)

poverty_cd_s1701 %>% 
  glimpse()

v2023 <- load_variables(2023, "acs5/subject", cache = TRUE)

v2023 %>% glimpse()

v2023 %>% 
  filter(name == 'S1701_C01_001') %>% 
  glimpse()

data("fips_codes")

states <- fips_codes %>% 
  select(state, state_code) %>% 
  distinct()

poverty_cd_s1701_labels <- poverty_cd_s1701 %>% 
  left_join(v2023,
            by = c("variable" = "name")) %>% 
  mutate(state_code = substr(GEOID, 1, 2)) %>% 
  left_join(states)

poverty_cd_s1701_labels %>% 
  glimpse()
```

```{r}
# takes too long
# poverty_cd_s1701_labels %>% 
#   pull(geometry) %>%
#   plot()

```

```{r}

poverty_cd_s1701_labels %>% 
  filter(state == 'IL') %>% 
  ggplot(aes(fill = estimate)) + 
  geom_sf()

```


```{r}


v2023 %>% 
  filter(name == 'S1701_C03_001') %>% 
  glimpse()


poverty_cd_s1701_labels %>% 
  filter(variable == 'S1701_C03_001') %>% 
  shift_geometry() %>% 
  ggplot(aes(fill = estimate)) + 
  geom_sf()

```


```{r}

poverty_cd_s1701_labels %>% 
  filter(variable == 'S1701_C03_001') %>% 
  shift_geometry() %>% 
  ggplot(aes(fill = estimate)) + 
  geom_sf() + 
  scale_fill_distiller(palette = "RdPu", 
                       direction = 1) + 
  labs(title = "Poverty Rate By Congressional District",
       caption = "Data source: 2023 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void()

```


```{r}
# Puerto Rico is substantially more poor than the rest of the US

poverty_cd_s1701_labels %>% 
  filter(variable == 'S1701_C02_001',
         state != 'PR') %>% 
  shift_geometry() %>% 
  ggplot(aes(fill = estimate)) + 
  geom_sf() + 
  scale_fill_distiller(palette = "RdPu", 
                       direction = 1) + 
  labs(title = "Population in Poverty By Congressional District",
       caption = "Data source: 2023 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void()
```

https://docs.google.com/spreadsheets/d/13XkF59JKzvw4SeSq5mbgIFrJfYjK4amg9JoQE5e9grQ/edit?gid=1250379179#gid=1250379179

```{r}
#"C:\Users\mkuhn\Documents\projects\personal\DataBlog\posts\MedicaidFundingImpact\data\original\HexCDv31\HexCDv31.shp"

cd_hex <-
  sf::read_sf('data/original/HexCDv31/HexCDv31.shp')

cd_hex %>% 
  ggplot(aes(fill = GEOID)) + 
  geom_sf() + 
  theme(legend.position="none")


```

```{r}

pov_data <-
  poverty_cd_s1701_labels  %>% 
  filter(variable == 'S1701_C02_001',
         state != 'PR') %>% 
    sf::st_drop_geometry() %>% 
    tibble()

cd_hex_s1701_labels <-
  cd_hex %>% 
    left_join(pov_data)


cd_hex_s1701_labels %>% 
  ggplot(aes(fill = estimate)) + 
  geom_sf() + 
  scale_fill_distiller(palette = "RdPu", 
                       direction = 1) + 
  labs(title = "Population in Poverty By Congressional District",
       caption = "Data source: 2023 5-year ACS, US Census Bureau",
       fill = "ACS estimate") + 
  theme_void()

```



```{r}
# Transforming data for hexbin layout using Leaflet
cd_hex %>% 
  leaflet() %>% 
  addTiles() %>% 
  addPolygons(weight = 0.5,
              opacity = 1,
              color = "white",
              fillOpacity = 0.8)
```


```{r}
library(r2d3)


```


```{r}
library(leaflet)
library(dplyr)
library(sf)
library(tigris)
library(tidycensus)

# Transforming data for hexbin layout using Leaflet
poverty_cd_s1701_labels %>% 
  filter(variable == 'S1701_C02_001',
         state != 'PR',
         !is.na(estimate)) %>%  # Remove missing values
  mutate(centroid = st_centroid(geometry)) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addPolygons(fillColor = ~colorNumeric("RdPu", estimate)(estimate),
              weight = 0.5,
              opacity = 1,
              color = "white",
              fillOpacity = 0.8,
              popup = ~paste0("Poverty Estimate: ", estimate)) %>% 
  addLegend(pal = colorNumeric("RdPu", poverty_cd_s1701_labels$estimate),
            values = poverty_cd_s1701_labels$estimate,
            title = "ACS Estimate",
            opacity = 1)

```

